config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "checklists#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # 1️⃣ Show all checklists
  # get '/checklists', to: 'checklists#index'

  # 2️⃣ Create new checklist
  # get '/checklists/new', to: 'checklists#new'
  # post '/checklists', to: 'checklists#create'

  resources :checklists, only: [:index, :new, :create, :show, :destroy, :edit, :update] do
    resources :tasks, only: [:new, :create, :edit, :update, :destroy, :show] do # only missing index
    # In contrast, a collection route acts on the entire collection of resources, rather than on a specific member. For example, a new or index action in a controller usually acts on the entire collection of resources, rather than a specific member of that collection.
      member do
        patch :completed
      end
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/checklist.rb
class Checklist < ApplicationRecord
  belongs_to :user
  has_many :tasks

  # enum not working atm
  enum :category, { gym: 0, airport: 1, roadtrip: 2, other: 3 }
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :checklist

  # why wouldn't we define this method in the TasksController?

  def completed?
    completed == true
    # this method checks whether the task has been completed and if yes, applies styling conditions to mark task as completed
  end
end

app/models/user.rb
class User < ApplicationRecord
  # This application wouldn't run without adding this line. Why?
  attr_accessor :first_name
  attr_accessor :last_name

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/checklists_controller.rb
class ChecklistsController < ApplicationController
  def index
    @checklists = Checklist.all
  end

  def new
    @checklist = Checklist.new
  end

  def create
    @checklist = Checklist.new(checklist_params)
    @checklist.user_id = current_user.id
    if @checklist.save
      redirect_to checklists_path(@checklist), notice: 'Checklist created successfully'
    else
      render :new
    end
  end

  def show
    @checklist = Checklist.find(params[:id])
  end

  def edit
    @checklist = Checklist.find(params[:id])
  end

  def update
    @checklist = Checklist.find(params[:id])
    @checklist.update(checklist_params)
    redirect_to checklist_path(@checklist)
  end

  def destroy
    @checklist = Checklist.find(params[:id])
    if @checklist.destroy
      flash[:success] = "Checklist has been deleted"
    else
      flash[:error] = "Checklist could not be deleted"
    end
    redirect_to root_url, status: :see_other
  end

  private

  def checklist_params
    params.require(:checklist).permit(:title, :category, :description)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # Skipping login for some pages
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :set_checklist
  before_action :set_task, except: [:create]
    # we don't wanr it on the create method because it's only after that method has been executed that the ID is created

  # method 'new' not needed

  def create
    @task = @checklist.tasks.create(task_params)
    # @task.user_id = current_user.id

    if @task.save
      redirect_to @checklist, notice: 'Task added successfully'
    else
      render :new
    end
  end

  def destroy
    # @task = @checklist.tasks.find(params[:id]) - stay DRY - this is not needed anymore because now we have before_action :set_task, except: [:create]
    if @task.destroy
      flash[:success] = "Task has been deleted"
    else
      flash[:error] = "Task could not be deleted"
    end
    redirect_to @checklist, status: :see_other
  end

  def completed
    @task.update_attribute(:completed, true)
    redirect_to @checklist, notice: "Task completed"
  end

  private

  def set_checklist
    @checklist = Checklist.find(params[:checklist_id])
  end

  def set_task
    @task = @checklist.tasks.find(params[:id])
  end

  def task_params
    # it's recommended to use the require method when you're confident that a certain parameter must be present in the params hash, as it raises a more informative error message if it's not.
    params.require(:task).permit(:title, :details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/checklists/edit.html.erb
<h1 class="todo_list_title">Edit your to-do list</h1>

<%= simple_form_for(@checklist, html: { class: "forms" }) do |f| %>
  <%= f.input :title %>
  <%= f.input :category, collection: Checklist.categories.keys %>
  <%= f.input :description %>
  <div class="submit-container">
    <%= f.submit %>
  </div>
<% end %>

<div class="links">
  <%= link_to 'Cancel', checklists_path %>
</div>

app/views/checklists/index.html.erb
<h1 class="page_title">checklist <br> central </h1>

<div class="container d-flex justify-content-start gap-2" style="margin-top: 200px;">
  <%= link_to "all", new_checklist_path, class: "status-selected" %>
  <%= link_to "gym", new_checklist_path, class: "status-unselected" %>
  <%= link_to "airport", new_checklist_path, class: "status-unselected" %>
  <%= link_to "other", new_checklist_path, class: "status-unselected" %>
</div>

<% @checklists.each do |checklist| %>

  <%# classes wrapping up title and description %>
  <div class="index_row clearfix container">
    <%= link_to checklist_path(checklist) do %>
      <h2 class="todo_list_title"><%= checklist.title %></h2>
      <p class="todo_list_sub_title"><%= checklist.description %></p>
    <% end %>
  </div>

<% end %>


<div class="links">
  <%= link_to "New Checklist", new_checklist_path %>
  <%# , class: "btn btn-primary" %>
</div>

app/views/checklists/new.html.erb
<%# form to create new checklist  %>
<%# could create a class for forms to style all forms %>

<h1 class="todo_list_title">New Checklist</h1>

<%= simple_form_for(@checklist, html: { class: "forms" }) do |f| %>
  <%= f.input :title %>
  <%= f.input :category, collection: Checklist.categories.keys %>
  <%= f.input :description %>
  <div class="submit-container">
    <%= f.submit %>
  </div>
<% end %>


<div class="links">
  <%= link_to 'Back', url_for(:back) %>
</div>

app/views/checklists/show.html.erb
<h2 class="todo_list_title"><%= @checklist.title %></h2>
<p class="todo_list_sub_title"><%= @checklist.description %></p>

<div id="tasks_wrapper">
  <%= render @checklist.tasks %>
  <div id="form">
    <%= render "tasks/form" %>
  </div>
</div>

<div class="links">
  <%= link_to 'Edit', edit_checklist_path(@checklist) %>
  <%= link_to 'Back', url_for(:back) %>
  <%= link_to "Delete", checklist_path(@checklist), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
  <%= link_to 'All lists', checklists_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskTracker</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/flashes" %> <%# relevant for devise authentication %>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<p>Not in use at the moment.</p>

app/views/shared/_flashes.html.erb
<%# flash alerts for devise/authentication %>
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm">
  <div class="container-fluid">

    <div id="navbarSupportedContent">
      <%# This line creates a div element that contains the collapsible content of the navigation bar. %>
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">

            <%# menu icon %>
            <a href="#" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fa-solid fa-bars-staggered menu-icon"></i>
            </a>

            <%# dropdown menu %>
            <div class="dropdown-menu dropdown-menu-end" style="margin-top: 30px;" aria-labelledby="navbarDropdown">
              <%= link_to "Your checklists", root_url, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/tasks/_form.html.erb
<%= form_for([@checklist, @checklist.tasks.build]) do |f| %>
  <%= f.text_field :title, placeholder: "New Task" %>
  <%# <%= f.text_field :details, placeholder: "Details" %>
  <%= f.submit %>
<% end %>

app/views/tasks/_task.html.erb
<div class="row clearfix">
  <% if task.completed? %>
    <div class="complete">
      <%= link_to completed_checklist_task_path(@checklist, task.id), data: { turbo_method: :patch } do %>
        <i style="opacity: 0.4;" class="fa-solid fa-check"></i>
      <% end %>
    </div>
    <div class="task">
      <p style="opacity: 0.4;"><strike><%= task.title %></strike></p>
    </div>
    <div class="trash">
      <%= link_to checklist_task_path(@checklist, task.id), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
        <i class="fa-regular fa-trash-can"></i>
      <% end %>
    </div>
  <% else %>
  <%# if the task has not been marked as completed, then show the task content(or title?) in its normal form.  %>
    <div class="complete">
      <%= link_to completed_checklist_task_path(@checklist, task.id), data: { turbo_method: :patch } do %>
        <i class="fa-solid fa-check"></i>
      <% end %>
        <%# checklist_task_path(@checklist, task.id) is actually where I want to be redirected to, once the action has been completed %>

        <%# It's a route helper method that generates a URL for the destroy action of the TasksController for a specific task belonging to a given Checklist object.
        The @checklist object is passed in as an argument to the route helper method to generate the correct URL. %>
    </div>
    <div class="task">
      <p><%= task.title %></p>
    </div>
    <div class="trash">
      <%= link_to checklist_task_path(@checklist, task.id), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
        <i class="fa-regular fa-trash-can"></i>
      <% end %>
    </div>
  <% end %>
</div>